# Generated by Django 4.2.5 on 2023-11-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_users_sex'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '커뮤니티 게시글', 'verbose_name_plural': '커뮤니티 게시글'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
        migrations.RemoveField(
            model_name='article',
            name='view',
        ),
        migrations.AddField(
            model_name='article',
            name='contents',
            field=models.TextField(default='', verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='article',
            name='writer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.users', verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='등록시간'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='제목'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='Community_board',
        ),
    ]
