# Generated by Django 4.2.7 on 2023-12-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
