"""
Django settings for fourtuna project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from sshtunnel import SSHTunnelForwarder
import mysql.connector

# SSH_TUNNEL = SSHTunnelForwarder(
#     ('121.182.56.212', 22),
#     ssh_username='b1uesoda',
#     ssh_password='s5584747',
#     ssh_proxy_enabled=True,
#     remote_bind_address=('172.30.1.24', 3306),
# )

# SSH_TUNNEL.start()


with SSHTunnelForwarder(
    ('121.182.56.212', 22),  # 원격 서버의 주소와 포트
    ssh_username='b1uesoda',
    ssh_password='s5584747',
    remote_bind_address=('172.30.1.24', 3306)  # 원격 서버의 호스트와 포트
) as tunnel:
    print("SSH 서버에 성공적으로 연결되었습니다.")
    # MySQL 연결 설정
    db_host = '127.0.0.1'
    db_port = '3306'
    db_user = 'root'
    db_password = '20-72008672'
    db_name = 'GSMOA'

    # 연결 객체 생성
    conn = mysql.connector.connect(
      host=db_host,
      port=db_port,
      user=db_user,
      password=db_password,
      database=db_name
    )
    # 연결 확인
    if conn.is_connected():
      print("MySQL에 성공적으로 연결되었습니다.")
    else:
      print("MySQL에 연결할 수 없습니다.")



    

# SSH 연결 확인


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*ar!ldq3kg35%agz2b()7i$8ju&cr!4@=3tz&yzl6q6fjo8u2m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gsmoa.apps.GsmoaConfig',
    'user.apps.UserConfig',
    'contestdb.apps.ContestdbConfig',
    'teaming.apps.TeamingConfig',
    'chatting.apps.ChattingConfig',
    'community.apps.CommunityConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fourtuna.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fourtuna.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases




# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.bac9kends.mysql',
#         'HOST': 'localhost',  # SSH 터널을 통해 연결되므로 localhost로 설정
#         'PORT': '3306',
#         'NAME': 'GSMOA',
#         'USER': 's5584747',
#         'PASSWORD': 's5584747',
#     }
# }




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
