server:
  port: 0

spring:
  application:
    name: Contest-Server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://spring-db-gsmoa.clcmmk2ygw1j.ap-northeast-2.rds.amazonaws.com/spring-DB
    username: root
    password: 20-72008672
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  main:
    allow-bean-definition-overriding: true
