# Generated by Django 4.2.5 on 2023-10-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsmoa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contest',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
