# Generated by Django 4.2.5 on 2023-11-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_accounts_alter_accounts_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='사용자 이름')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('useremail', models.CharField(max_length=128, verbose_name='사용자 이메일')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'users',
            },
        ),
        migrations.DeleteModel(
            name='accounts',
        ),
    ]
