# Generated by Django 4.2.5 on 2023-11-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_users_delete_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=300, verbose_name='비밀번호'),
        ),
    ]
