# Generated by Django 4.2.5 on 2023-11-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='introduction',
            field=models.CharField(default='', max_length=300, verbose_name='자기소개'),
        ),
        migrations.AddField(
            model_name='users',
            name='sex',
            field=models.CharField(default='', max_length=2, verbose_name='사용자 성별'),
        ),
        migrations.AddField(
            model_name='users',
            name='userid',
            field=models.CharField(default='', max_length=32, verbose_name='아이디'),
        ),
    ]
