# Generated by Django 4.2.5 on 2023-11-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_users_introduction_users_sex_users_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='introduction',
            field=models.CharField(max_length=300, verbose_name='자기소개'),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(max_length=2, verbose_name='사용자 성별'),
        ),
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.CharField(max_length=32, verbose_name='아이디'),
        ),
    ]
