# Generated by Django 4.2.5 on 2023-11-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_users_introduction_alter_users_sex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='sex',
        ),
    ]
