# Generated by Django 4.2.6 on 2023-12-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest_info",
            name="keyword",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contest_info",
            name="link",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="contest_info",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
