# Generated by Django 4.2.6 on 2023-12-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contest", "0004_alter_contest_info_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="my_contest",
            old_name="login_id",
            new_name="login",
        ),
        migrations.AlterField(
            model_name="contest_info",
            name="image",
            field=models.ImageField(upload_to="This/fourtuna/static/contest_img"),
        ),
    ]
