# Generated by Django 4.2.6 on 2023-12-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contest", "0007_alter_contest_info_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest_info",
            name="host",
            field=models.CharField(max_length=100),
        ),
    ]
