# Generated by Django 4.2.6 on 2023-12-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contest", "0008_alter_contest_info_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest_info",
            name="content",
            field=models.TextField(null=True),
        ),
    ]
