# Generated by Django 4.2.5 on 2023-10-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=10)),
                ('user_nick_name', models.CharField(max_length=12)),
                ('user_pw', models.CharField(max_length=12)),
            ],
        ),
    ]
